version: "3.1"

services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${COMPOSE_PROJECT_NAME}_mailhog
    ports:
      - 127.0.0.1:8125:8025

  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
        - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    volumes:
      - ../logs/mysql:${MYSQL_LOG_DIR}
      - ../database:${MYSQL_DATA_DIR}
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      public_net:
        ipv4_address: ${MYSQL_IP}
    environment:
      - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
      - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

      # Are these still necessary?
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  apache:
    build:
      context: ./apache
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
    container_name: ${COMPOSE_PROJECT_NAME}_apache
    extra_hosts:
      - "vore.test:127.0.0.1"
    hostname: vore.test
    ports:
      - ${APACHE_EXPOSED_PORT}:80
    networks:
      public_net:
        ipv4_address: ${APACHE_IP}
    environment:
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
      - PHP_IP=${PHP_IP}
      - PHP_APP_DIR=${PHP_APP_DIR}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
    volumes:
      - ../:/var/www/html
      - ../logs/docker/apache:${APACHE_ROOT_DIR}/logs
      #- ./apache/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      #- ./apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      #- ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    working_dir: /var/www/html

  php:
    build:
      context: ./php-fpm
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - PHP_ROOT_DIR=${PHP_ROOT_DIR}
    container_name: ${COMPOSE_PROJECT_NAME}_php
    expose:
      - 9000
    working_dir: ${PHP_APP_DIR}
    volumes:
      - ..:${PHP_APP_DIR}
      - ../logs/docker/php:${PHP_ROOT_DIR}/logs
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    depends_on:
      - apache
      - mysql
    networks:
      public_net:
        ipv4_address: ${PHP_IP}
    environment:
      - PHP_ROOT_DIR=${PHP_ROOT_DIR}
      - APACHE_IP=${APACHE_IP}
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
      - MYSQL_IP=${MYSQL_IP}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

networks:
  public_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
